WeatherMVC/Models/ErrorViewModel.cs
namespace WeatherMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WeatherMVC/Models/ViewModels/WeatherViewModel.cs
namespace WeatherMVC.Models.ViewModels
{
    public class WeatherViewModel
    {
        public int month { get; set; }
        public int year { get; set; }
        public List<Weather> weathersYearMonth = new List<Weather>();
    }
}

WeatherMVC/Models/Weather.cs
namespace WeatherMVC.Models
{
    public class Weather
    {
        public int Id { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Time { get; set; }
        public string T { get; set; }
        public string Vlaga { get; set; }
        public string Td { get; set; }
        public string Ps { get; set; }
        public string NaprVet { get; set; }
        public string SpeedVetra { get; set; }
        public string Oblach { get; set; }
        public string h { get; set; }
        public string VV { get; set; }
        public string pogoda { get; set; }
        public Weather()
        {

        }
        public Weather(List<string> nn)
        {

            Date = nn[0];
            Month = DateTime.Parse(nn[0]).Month.ToString();
            Year = DateTime.Parse(nn[0]).Year.ToString();
            Time = nn[1];
            T = nn[2];
            Vlaga = nn[3];
            Td = nn[4];
            Ps = nn[5];
            NaprVet = nn[6];
            SpeedVetra = nn[7];
            Oblach = nn[8];
            h = nn[9];
            VV = nn[10];
            pogoda = nn[11];

        }
    }

}

WeatherMVC/Controllers/AddExcelController.cs
using Microsoft.AspNetCore.Mvc;

namespace WeatherMVC.Controllers
{
    public class AddExcelController : Controller
    {

        IWebHostEnvironment _appEnvironment;
        public IActionResult AddExcel()
        {
            return View();
        }
        public AddExcelController(IWebHostEnvironment appEnvironment)
        {
            _appEnvironment = appEnvironment;
        }
        public async Task<IActionResult> AddFile(IFormFile uploadedFile)
        {
            if (uploadedFile != null)
            {
                // путь к папке Files
                string path = "DAL/Excel/" + uploadedFile.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream( path, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
                WeatherMVC.DAL.Repositories.WeatherRepository.UpdateDataFromExcel(path);
            }

            return RedirectToAction("AddExcel");
        }
    }
}

WeatherMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WeatherMVC.Models;

namespace WeatherMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WeatherMVC/Controllers/ShowExcelController.cs
using Microsoft.AspNetCore.Mvc;
using WeatherMVC.Models.ViewModels;

namespace WeatherMVC.Controllers
{
    public class ShowExcelController : Controller
    {
        public IActionResult Show()
        {

            return View();
        }
        public IActionResult ShowNew(int year, int month)
        {
            WeatherViewModel W = new WeatherViewModel();
            W.month = month;
            W.year = year;
            return View(W);
        }
    }
}

WeatherMVC/Views/AddExcel/AddExcel.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Add";
    Layout = "_LauoutS";
}

<h3>Выберите файл для загрузки</h3>
<form asp-action="AddFile" asp-controller="AddExcel" method="post" enctype="multipart/form-data">
    <input type="file" name="uploadedFile" multiple="multiple" /><br>
    <input type="submit" value="Загрузить" />
</form>

<h3>Все файлы</h3>

WeatherMVC/Views/Home/Index.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
    Layout = "_LauoutS";
}


<button><a asp-action="AddExcel" asp-controller="AddExcel" >Добавить</a></button>

<button><a asp-action="ShowNew" asp-controller="ShowExcel" asp-route-year="2010" asp-route-month="1">Показать</a></button>

WeatherMVC/Views/Shared/_LauoutS.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <h1>Погода в Москве(Общий хедер)</h1>
    <div>
        @RenderBody()
    </div>
    <footer>Общий футер</footer>
</body>
</html>

WeatherMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeatherMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeatherMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeatherMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WeatherMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeatherMVC/Views/ShowExcel/Components/WeatherYM/Default.cshtml
@model WeatherMVC.Models.ViewModels.WeatherViewModel
@{
    ViewData["Title"] = "View";

}
@if (Model != null)
{
    <table border="1">
        <tr>
        <th>Дата</th>
        <th>Время МСК</th><th>Е</th><th>Влажность</th><th>Td</th>
        <th>Давление</th>
        <th>Направление ветра</th>
        <th>Скорость ветра м/с</th>
        <th>Облачность</th><th>h</th><th>VV</th><th>Погодные явления</th>
        </tr>
   @for(int i = 0; i < @Model.weathersYearMonth.Count; i++)
    {
        <tr>
        <td>@Model.weathersYearMonth[i].Date</td>
        <td> @Model.weathersYearMonth[i].Time </td>
<td>@Model.weathersYearMonth[i].T </td>
<td>@Model.weathersYearMonth[i].Vlaga </td>
<td>@Model.weathersYearMonth[i].Td </td>
<td>@Model.weathersYearMonth[i].Ps </td>
<td>@Model.weathersYearMonth[i].NaprVet </td>
<td>@Model.weathersYearMonth[i].SpeedVetra </td>
<td>@Model.weathersYearMonth[i].Oblach </td>
<td>@Model.weathersYearMonth[i].h </td>
<td>@Model.weathersYearMonth[i].VV </td>
<td align="center">@Model.weathersYearMonth[i].pogoda </td>
         </tr>
         
    }
    </table>
}
else
{
    <h1>Данных нет</h1>
}

WeatherMVC/Views/ShowExcel/Show.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Show";
    Layout = "_LauoutS";
}

<h1>Show</h1>

<a asp-action="Index" asp-controller="Home">Back</a><p></p>
@{
    for (int z = 0; z < 4; z++)
    {
        <a asp-controller="ShowEx" asp-action="Show" asp-route-year=201@(z) asp-route-month="1">201@(z)</a>
    }
    <p></p>
    for (int j = 1; j <= 12; j++)
    {
        if (j < 10)
        {
            <a asp-controller="ShowEx" asp-action="Show" asp-route-year=@Model.year asp-route-month=@j>0@(j)</a>
        }
        else
        {
            <a asp-controller="ShowEx" asp-action="Show" asp-route-year=@Model.year asp-route-month=@j> @(j)</a>
        }

    }
    @if (Model.month < 10)
    {
        <h1>Данные за 0@(Model.month) / @Model.year</h1>
    }
    else
    {
        <h1>Данные за @(Model.month) / @Model.year</h1>
    }

    for (int i = 0; i < @Model.weathers.Count; i++)
    {
        <a>@Model.weathers[i].Date</a>
        <a> @Model.weathers[i].Time </a>
        <a>@Model.weathers[i].T </a>
        <a>@Model.weathers[i].Vlaga </a>
        <a>@Model.weathers[i].Td </a>
        <a>@Model.weathers[i].Ps </a>
        <a>@Model.weathers[i].NaprVet </a>
        <a>@Model.weathers[i].SpeedVetra </a>
        <a>@Model.weathers[i].Oblach </a>
        <a>@Model.weathers[i].h </a>
        <a>@Model.weathers[i].VV </a>
        <a>@Model.weathers[i].pogoda </a>

        <p></p>
    }
}

WeatherMVC/Views/ShowExcel/ShowNew.cshtml
@using WeatherMVC.Components;
@using WeatherMVC.Models;
@using System.IO
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "ShowNew";
}
<a asp-action="Index" asp-controller="Home">Back</a><p></p>
@{
    var i = Directory.GetFiles(@"DAL\Excel\").Count();
    for (int z = 0; z < i; z++)
    {
        <a asp-controller="ShowExcel" asp-action="ShowNew" asp-route-year=201@(z) asp-route-month="1">201@(z)</a>
    }
    <p></p>
    for (int j = 1; j <= 12; j++)
    {
        if (j < 10)
        {
            <a asp-controller="ShowExcel" asp-action="ShowNew" asp-route-year=@Model.year asp-route-month=@j>0@(j)</a>
        }
        else
        {
            <a asp-controller="ShowExcel" asp-action="ShowNew" asp-route-year=@Model.year asp-route-month=@j> @(j)</a>
        }

    }
    @if (Model.month < 10)
    {
        <h1>Данные за 0@(Model.month) / @Model.year</h1>
    }
    else
    {
        <h1>Данные за @(Model.month) / @Model.year</h1>
    }
}

<p>@await Component.InvokeAsync(nameof(WeatherYM), new{year=@Model.year,month=@Model.month})</p>